exclude: '^(build|dist|env|onsigntv_app_simulator.egg-info)/.+$'

# General
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

# Python
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    -   id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
