exclude: '^(build|dist|env|onsigntv_app_simulator.egg-info)/.+$'

# General
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: trailing-whitespace
    -   id: end-of-file-fixer

# Python
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.0
    hooks:
        # Run the linter.
    -   id: ruff
        args: [--fix]
    # Run the formatter.
    -   id: ruff-format

-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: prettier --write --print-width 120 --list-different --ignore-unknown
        language: node
        types_or: [css, less, scss, javascript, vue, ts]
        exclude: '^app_simulator/static/shim/Intl.min.js$'
